// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: watch2

#ifndef _WATCH2_UI_H
#define _WATCH2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void dot_a_Animation( lv_obj_t *TargetObject, int delay);
void timedot_Animation( lv_obj_t *TargetObject, int delay);
void datePanel_a_Animation( lv_obj_t *TargetObject, int delay);
void weatherPanel_a_Animation( lv_obj_t *TargetObject, int delay);
void weatherBg_a_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_initScreen
void ui_initScreen_screen_init(void);
void ui_event_initScreen( lv_event_t * e);
extern lv_obj_t *ui_initScreen;
extern lv_obj_t *ui_sysLoadTapsText;
// SCREEN: ui_watchScreen
void ui_watchScreen_screen_init(void);
void ui_event_watchScreen( lv_event_t * e);
extern lv_obj_t *ui_watchScreen;
extern lv_obj_t *ui_dotimg;
extern lv_obj_t *ui_TimePanel;
extern lv_obj_t *ui_hour;
extern lv_obj_t *ui_timedot;
extern lv_obj_t *ui_minute;
extern lv_obj_t *ui_datePanel;
extern lv_obj_t *ui_weekText;
extern lv_obj_t *ui_dateText;
extern lv_obj_t *ui_WeatherPanel;
extern lv_obj_t *ui_temperatureText;
extern lv_obj_t *ui_weatherText;
// SCREEN: ui_weatherScreen
void ui_weatherScreen_screen_init(void);
void ui_event_weatherScreen( lv_event_t * e);
extern lv_obj_t *ui_weatherScreen;
extern lv_obj_t *ui_weatherGroup;
extern lv_obj_t *ui_weatherItem;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_weatherBg;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_bg240_png);   // assets/bg240.png
LV_IMG_DECLARE( ui_img_sec_dot_png);   // assets/sec_dot.png
LV_IMG_DECLARE( ui_img_2018606726);   // assets/5@2x.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets/btn_bg_3.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets/call1.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
