// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: watch2

#include "../ui.h"

void ui_watchScreen_screen_init(void)
{
ui_watchScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_watchScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watchScreen, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_watchScreen, &ui_img_bg240_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_color(ui_watchScreen, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watchScreen, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dotimg = lv_img_create(ui_watchScreen);
lv_img_set_src(ui_dotimg, &ui_img_sec_dot_png);
lv_obj_set_width( ui_dotimg, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_dotimg, LV_SIZE_CONTENT);   /// 8
lv_obj_set_x( ui_dotimg, 0 );
lv_obj_set_y( ui_dotimg, 2 );
lv_obj_set_align( ui_dotimg, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_dotimg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dotimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_dotimg,4,118);

ui_TimePanel = lv_obj_create(ui_watchScreen);
lv_obj_set_width( ui_TimePanel, 180);
lv_obj_set_height( ui_TimePanel, 50);
lv_obj_set_align( ui_TimePanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TimePanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TimePanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_TimePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TimePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TimePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hour = lv_label_create(ui_TimePanel);
lv_obj_set_width( ui_hour, 70);
lv_obj_set_height( ui_hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hour, 30 );
lv_obj_set_y( ui_hour, 40 );
lv_obj_set_align( ui_hour, LV_ALIGN_CENTER );
lv_label_set_text(ui_hour,"00");
lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timedot = lv_label_create(ui_TimePanel);
lv_obj_set_width( ui_timedot, 10);
lv_obj_set_height( ui_timedot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_timedot, LV_ALIGN_CENTER );
lv_label_set_text(ui_timedot,":");
lv_obj_set_style_text_color(ui_timedot, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timedot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_timedot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timedot, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minute = lv_label_create(ui_TimePanel);
lv_obj_set_width( ui_minute, 70);
lv_obj_set_height( ui_minute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_minute, LV_ALIGN_CENTER );
lv_label_set_text(ui_minute,"00");
lv_obj_set_style_text_color(ui_minute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_minute, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_minute, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_datePanel = lv_obj_create(ui_watchScreen);
lv_obj_set_width( ui_datePanel, 118);
lv_obj_set_height( ui_datePanel, 45);
lv_obj_set_x( ui_datePanel, 0 );
lv_obj_set_y( ui_datePanel, 30 );
lv_obj_set_align( ui_datePanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_datePanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_datePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_datePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_datePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_datePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_datePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_datePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weekText = lv_label_create(ui_datePanel);
lv_obj_set_width( ui_weekText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weekText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_weekText, LV_ALIGN_CENTER );
lv_label_set_text(ui_weekText,"loading");
lv_obj_set_style_text_color(ui_weekText, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_weekText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_weekText, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dateText = lv_label_create(ui_datePanel);
lv_obj_set_width( ui_dateText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dateText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dateText, LV_ALIGN_CENTER );
lv_label_set_text(ui_dateText,"0000-00-00");
lv_obj_set_style_text_color(ui_dateText, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dateText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dateText, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherPanel = lv_obj_create(ui_watchScreen);
lv_obj_set_width( ui_WeatherPanel, 108);
lv_obj_set_height( ui_WeatherPanel, 37);
lv_obj_set_x( ui_WeatherPanel, 0 );
lv_obj_set_y( ui_WeatherPanel, -45 );
lv_obj_set_align( ui_WeatherPanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_WeatherPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_WeatherPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_WeatherPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WeatherPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_WeatherPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_WeatherPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temperatureText = lv_label_create(ui_WeatherPanel);
lv_obj_set_width( ui_temperatureText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperatureText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_temperatureText, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperatureText,"NA");
lv_obj_set_style_text_color(ui_temperatureText, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperatureText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperatureText, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherText = lv_label_create(ui_WeatherPanel);
lv_obj_set_width( ui_weatherText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_weatherText, LV_ALIGN_CENTER );
lv_label_set_text(ui_weatherText,"NA");
lv_obj_set_style_text_color(ui_weatherText, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_weatherText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_weatherText, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_watchScreen, ui_event_watchScreen, LV_EVENT_ALL, NULL);

}
