// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: watch2

#include "../ui.h"

void ui_weatherScreen_screen_init(void)
{
ui_weatherScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_weatherScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_weatherScreen, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weatherScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherGroup = lv_obj_create(ui_weatherScreen);
lv_obj_set_width( ui_weatherGroup, 224);
lv_obj_set_height( ui_weatherGroup, 77);
lv_obj_set_align( ui_weatherGroup, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_weatherGroup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_weatherGroup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_weatherGroup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_weatherGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_weatherGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_weatherItem = lv_obj_create(ui_weatherGroup);
// lv_obj_set_width( ui_weatherItem, lv_pct(33));
// lv_obj_set_height( ui_weatherItem, lv_pct(100));
// lv_obj_set_align( ui_weatherItem, LV_ALIGN_CENTER );
// lv_obj_set_flex_flow(ui_weatherItem,LV_FLEX_FLOW_COLUMN);
// lv_obj_set_flex_align(ui_weatherItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
// lv_obj_clear_flag( ui_weatherItem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
// lv_obj_set_style_bg_color(ui_weatherItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_bg_opa(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_border_color(ui_weatherItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_border_opa(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_border_width(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_left(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_right(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_top(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_bottom(ui_weatherItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_Label3 = lv_label_create(ui_weatherItem);
// lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
// lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_Label1 = lv_label_create(ui_weatherItem);
// lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
// lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_Label2 = lv_label_create(ui_weatherItem);
// lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
// lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherBg = lv_img_create(ui_weatherScreen);
lv_img_set_src(ui_weatherBg, &ui_img_2018606726);
lv_obj_set_width( ui_weatherBg, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_weatherBg, LV_SIZE_CONTENT);   /// 51
lv_obj_set_align( ui_weatherBg, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_weatherBg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_weatherBg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_weatherScreen, ui_event_weatherScreen, LV_EVENT_ALL, NULL);

}
